### ISSUE TITLE
제안서 리뷰

### ISSUE THREAD

**Issue by MisooKim2** [seoojunn/PY202309-P#1]
1. 유저 프로필에 담겨있는 정보가 구체적으로 어떤걸까요? 구체화가 필요해보입니다.
2. 만약 유저가 이미 알고 있는/작성한 레시피와 동일한 레시피가 출력되면 어떻게 되나요? 해당 처리가 추가될 필요가 있어보입니다. 
- 변경 사항은 제안서는 수정하지 마시고, 1차 진척보고서에 반영하여 주시길 바랍니다

**Comment by seoojunn** [comment]
1. 유저 프로필에 담겨있는 정보는 재료 정보입니다.
2. 재료를 입력하면 그에 맞는 레시피를 출력하는 거라서 레시피 파일은 웹크롤링을 통해 이미 존재합니다!
